pipeline:

# staging

  build_stg:
    image: ubuntu:xenial
    commands:
      # we don't use rvm as install scripts need to be run under bash and not sh
      # and Drone does not support custom shells yet. https://github.com/drone/drone/issues/1409
      - apt-get update
      - apt-get install -y wget git gcc make ruby2.3-dev libffi-dev zlib1g-dev
      - gem install bundler
      - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 8
      - nvm use 8
      - npm install -g yarn
      - bash -x ./bin/automated
    when:
      branch: drone-file

#  docker_stg:
#    image: plugins/docker
#    registry: quay.io
#    repo: quay.io/srcd/blog
#    secrets: [ docker_username, docker_password ]
#    tag: ${DRONE_COMMIT_SHA:0:7}
#    file: Dockerfile
#    when:
#      branch: master
#
#  helm_deploy_stg:
#    image: quay.io/ipedrazas/drone-helm
#    skip_tls_verify: true
#    chart: ./helm-charts/blog
#    release: blog
#    prefix: STG
#    secrets: [ STG_API_SERVER, STG_KUBERNETES_TOKEN ]
#    values: ingress.globalStaticIpName=blog-srcd-run,ingress.hostname=blog.srcd.run,image.repository=quay.io/srcd/blog,image.tag=${DRONE_COMMIT_SHA:0:7}
#    tiller_ns: kube-system
#    debug: true
#    wait: true
#    when:
#      branch: master
#      #
